### ISSUE TITLE
SVD Did not converge

### ISSUE THREAD

**Issue by ELLI-E** [ELLI-E/RedQSOYoRiS#2]
Ran code on object 39627770262716602. Received following error log. Attempted to run with and without masking nearby sources without any changes. 
[decompositionError.log](https://github.com/user-attachments/files/17618658/decompositionError.log)

**Comment by ELLI-E** [comment]
Image of the data and segmentation map for reference:
![image](https://github.com/user-attachments/assets/1f5c8734-d616-47ae-9acf-760e141cf01c)

**Comment by Tang-SL** [comment]
This error means the fitting with PSO algorithm could not converge, very likely beacause of source No.4 at the edge. It is truncated and cannot be well-fitted with a sersic profile. Suggestion would be masking that source.

**Comment by ELLI-E** [comment]
> This error means the fitting with PSO algorithm could not converge, very likely beacause of source No.4 at the edge. It is truncated and cannot be well-fitted with a sersic profile. Suggestion would be masking that source.

Here is the data used for the fit with the companions masked, and the corresponding error log. It doesn't seem to make much difference

[decompositionError.log](https://github.com/user-attachments/files/17618772/decompositionError.log)
![image](https://github.com/user-attachments/assets/b5e0af0e-6225-47b1-9a1a-fcbfd6511255)

**Comment by Tang-SL** [comment]
Maybe there are infinite or nan numbers in your data? Try drop those pixels as well if any?
